package co.edu.udea.epm.dto;
// Generated 27-may-2018 20:11:32 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Sector generated by hbm2java
 */
public class Sector implements java.io.Serializable {

	private int codigo;
	private String nombre;
	private String municipio;
	

	public Sector() {
	}

	public Sector(int codigo) {
		this.codigo = codigo;
	}

	public Sector(int codigo, String nombre, String municipio) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.municipio = municipio;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}
}
