package co.edu.udea.epm.dto;
// Generated 27-may-2018 20:11:32 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Sesion generated by hbm2java
 */
public class Sesion implements java.io.Serializable {

	private int codigo;
	private Empleado empleado;
	private Usuario usuario;

	public Sesion() {
	}

	public Sesion(int codigo) {
		this.codigo = codigo;
	}

	public Sesion(int codigo, Empleado empleado, Usuario usuario) {
		this.codigo = codigo;
		this.empleado = empleado;
		this.usuario = usuario;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
}
