package co.edu.udea.epm.dto;
// Generated 27-may-2018 20:11:32 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Solicitud generated by hbm2java
 */
@XmlRootElement
public class Solicitud implements java.io.Serializable {

	private int codigo;
	private Sector sector;
	private Sesion sesion;
	private String estado;
	private String tipoDaño;
	private Character prioridad;

	public Solicitud() {
	}

	public Solicitud(int codigo) {
		this.codigo = codigo;
	}

	public Solicitud(int codigo, Sector sector, Sesion sesion, String estado, String tipoDaño, Character prioridad) {
		this.codigo = codigo;
		this.sector = sector;
		this.sesion = sesion;
		this.estado = estado;
		this.tipoDaño = tipoDaño;
		this.prioridad = prioridad;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public Sector getSector() {
		return this.sector;
	}

	public void setSector(Sector sector) {
		this.sector = sector;
	}

	public Sesion getSesion() {
		return this.sesion;
	}

	public void setSesion(Sesion sesion) {
		this.sesion = sesion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getTipoDaño() {
		return this.tipoDaño;
	}

	public void setTipoDaño(String tipoDaño) {
		this.tipoDaño = tipoDaño;
	}

	public Character getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(Character prioridad) {
		this.prioridad = prioridad;
	}

}
